# -*- coding: utf-8 -*-
"""hw1_binary_hex_converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBLOiiKjSTXqjyxKE-d4e9Vm5T1GNuRH
"""

def two(num): #算二進位
  numa = num
  answera = ""
  while numa > 0:
    keepa = numa % 2
    answera = str(keepa) + answera
    numa = numa // 2
  return answera


def sixteen(num): #算十六進位
  numb = num
  answerb = ""
  while numb > 0:
    keepb = numb % 16
    if keepb == 10:
      keepb = "A"
    elif keepb == 11:
      keepb = "B"
    elif keepb == 12:
      keepb = "C"
    elif keepb == 13:
      keepb = "D"
    elif keepb == 14:
      keepb = "E"
    elif keepb == 15:
      keepb = "f"
    answerb = str(keepb) + answerb
    numb = numb // 16
  return answerb

num = input("給我一個0~255之間的十進位數字：")
num = int(num)
if num <= 255 and num >= 0:
  resulttwo = two(num)
  resultsixteen = sixteen(num)


  print("它的二進位制是", resulttwo)
  print("它的十六進位制是", resultsixteen)

else:
 print("超出範圍了OwO")